### PR TITLE
reload: Try to reload polybar

### PR DESCRIPTION
**Pull request by sphaugh**
Not sure if this is the "right" way, but polybar doesn't seem to reload unless its configuration is touched, so could we try this?

### CODE REVIEW

**Comment by dylanaraps** [comment]
Does this work on your end? I

**Comment by sphaugh** [comment]
Will test this in an hour or so

**Comment by sphaugh** [comment]
Works perfectly :)

**Comment by dylanaraps** [comment]
Thanks! :)

**Pull request merged**
