### PR TITLE
os: Add support for macOS

### PR DESCRIPTION
**Pull request by dylanaraps**
Note: For those who read this.

Support for macOS is possible (iTerm2 only), the only issue is that I can't get a macOS machine I can test on. What I need to test is iTerm2's proprietary escape sequences. 

iTerm2 supports a similar sequence to the Linux terminals to change colors but it works differently and the reference page in the docs isn't very clear. 

Here's the page (Scroll down to "Change the color palette"): 

> https://www.iterm2.com/documentation-escape-codes.html

> Change the color palette
>
> `^[]Pnrrggbb^[\`
>
> Replace "n" with:
>
>    `0-f (hex) = ansi color`
    `g = foreground`
    `h = background`
    `i = bold color`
    `j = selection color`
    `k = selected text color`
   ` l = cursor`
    `m = cursor text`
>
> rr, gg, bb are 2-digit hex value (for example, "ff"). Example in bash that changes the foreground color blue:
>
> `echo -e "\033]Pg4040ff\033\\"`

Basically what we need to figure out is the exact sequences we need to modify `background`, `foreground`, `cursor` and colors `0-15`. If anyone with a macOS system would like to test I'd be grateful as I can't find these sequences in use anywhere as a reference.

More info:

- https://gitlab.com/gnachman/iterm2/issues/454

### CODE REVIEW

**Comment by L3rchal** [comment]
Hi,
    this somehow gives me error unable to open database ```/Library/Application Support/Dock/desktoppicture.db``` so I tried to fix but for some reason I wasn't able to open database and edit it. However when I am using *osascript* command then it's working. 
```python3
if OS == "Darwin":
        cmd = """osascript -e 'tell application "Finder" to set desktop picture to POSIX file "%s"'""" % (os.path.abspath(img)) # must be one liner otherwise it's not working
        subprocess.Popen(cmd,shell=True)
```
There's no need to kill Dock. Anyway this changes wallpaper and the output seems ok but terminal appearance does not change. (Apple Terminal.app)

Cheers

**Comment by dylanaraps** [comment]
Ok so from googling I've found out that the `osascript` wallpaper command broke in a recent version of macOS and the `sqlite3` command from this PR is the newest working method. It looks like we'll have to implement a macOS version check to determine which wallpaper command to use. 

There's no way to make `pywal` work with the stock Terminal.app, the only macOS terminal that supports the escape sequences required is iTerm2. Can you try this PR in iTerm2 and let me know what works? I haven't got a macOS system to test this on.

**Comment by L3rchal** [comment]
The thing with osascript sucks.  Anyway I'll try the sqlite3 again. I tried iterm2 and there is no change as well.

**Comment by dylanaraps** [comment]
Closed in favor of #64. 

@L3rchal can you test #64?

**Pull request closed without merging**
