### PR TITLE
[Feature] Add themer template

### PR DESCRIPTION
**Pull request by ryuta69**
Themer is a great OSS which generates various editor themes, terminal themes, and themes for other apps.

https://github.com/mjswensen/themer

Themer can run with user color-set. 
I'd like to make color-set with pywal.
So I created PR.

### CODE REVIEW

**Comment by ryuta69** [comment]
Test failed for non-related reason, and it looks this error exists before this PR.

```
$ flake8 pywal tests setup.py
pywal/export.py:61:80: E501 line too long (97 > 79 characters)
pywal/export.py:68:80: E501 line too long (81 > 79 characters)
The command "flake8 pywal tests setup.py" exited with 1.
```

**Comment by ryuta69** [comment]
Tests are fixed here

https://github.com/dylanaraps/pywal/pull/546

**Comment by ryuta69** [comment]
@dylanaraps 
Hope this PR will be merged....

**Comment by dylanaraps** [comment]
Apologies for the delay. Thanks for the PR.

**Comment by ryuta69** [comment]
Thank you very much for review!
I love your products!

**Pull request merged**
