### PR TITLE
api: Start work on a proper api.

### PR DESCRIPTION
**Pull request by dylanaraps**
The aim of this PR is to make `pywal` easily useable in other python projects. (Namely `wpgtk`) This PR will implement a clear api so that other scripts or programs can use individual parts of `pywal`.

This also means unhardcoding all of `pywal`'s directories and cache locations. ;)

**Documentation:** https://github.com/dylanaraps/pywal/wiki/%5BVery-WIP%5D-How-to-use-the-API

Changes:

- Exposes main functions to `__init__.py` and allows `pywal` to be used as a module.
- Remove all linter exceptions from comments.
- Removed all unneeded comments.
- Renamed `magic` module to `colors`.
- Renamed functions to remove redundency. 
    `image.get_image()` --> `image.get()`
- Tests now cover random images from dir.
- Files are now saved safely. 
    - (Parent dirs are created if they don't exist.)

TODO:

- [x] Finish writing api functions.
- [x] Move functions from `__init__.py` to `wal.py`.
- [x] Use functions from `wal.py` in `__main__.py`.
- [x] Modify `reload_` functions to take a file path.
    - They're hardcoded right now.
- [x] Write documentation.
    - [x] A wiki page sounds good.
    - [x] https://github.com/dylanaraps/pywal/wiki/%5BVery-WIP%5D-How-to-use-the-API

### CODE REVIEW

**Comment by deviantfero** [comment]
yes, yes, yes, Thanks Dylan, I'm currently working on `wpgtk` myself, at a slow pace though because _work_, I'm just getting the code prettier and removing as much garbage as I can, I was just a beginner when I started the project. I'm trying to get it nice and ready  for a pip installation, of course that will require your api.

anyway,  I think the example looks great so far, It would be great to have a function for each kind of export you want to make, or maybe just a generic one like this:

```
colors = pywal.create_pallete(image)

pywal.export_css(colors, path_to_file)
pywal.export_xres(colors, path_to_file)
pywal.export_plain(colors, path_to_file)

# another approach; specify export type in function
pywal.export_colors(colors, path_to_file, "css")
pywal.export_colors(colors, path_to_file, "xres")

# you get the idea
```

as far as I can see, once you achieve this, integration should be fairly simple, it seems to have the flexibility I need to integrate it.

just another suggestion regarding the exports.
I plan to add the ability to define "custom exports" in wpgtk's interface with the use of a config file.
so a function like: `pywal.custom_export(colors, prefix, postfix, path_to_file)`, would be excelent, maybe I can do it myself (a pull request regarding this feature) later on in the development of the API.

thanks for everything. talk to you soon!

**Comment by dylanaraps** [comment]
I've documented the functions I've implemented thus far. Please let me know if the page explains things well enough or if there's something you're unsure about.

Everything is still subject to change and I want to get the api perfect before I release it since making changes later will be much harder. :)

Note: I haven't forgotten about the export functions, they'll take a little longer since I need to refactor parts of the script.

**Comment by deviantfero** [comment]
Yes, the instructions are clear, still I do have a question, with `cache_dir` and `template_dir`, do I get to specify the filename of the exported file? or just the directory?

**Comment by dylanaraps** [comment]
Just the directory, the exported files inherit the template name.

Example:

```sh
templates/colors.css --> export_dir/colors.css
templates/colors.sh --> export_dir/colors.sh
```

The `export_all_templates()` function loops over the template directory and exports everything in it. I'm going to add some functions to specify individual files etc later on in this PR.

**Comment by deviantfero** [comment]
great, I'll keep an eye on it and give any suggestions if I have any.

**Comment by dylanaraps** [comment]
I've added a new function to the api will lets you specify which file to export. There's a list of available arguments for the template file as well as some examples in the wiki page below.

The api seems complete now, please try it out and let me know if anymore changes need to be made or features added. :)

Example:

```py
pywal.export(colors, "colors.css")

# Using a custom cache dir.
cache_dir = pathlib.Path("/tmp/wal")
pywal.export(colors, "colors.css", cache_dir)
```

See: https://github.com/dylanaraps/pywal/wiki/[Very-WIP]-How-to-use-the-API#pywalexportcolors-file-cache_dir

**Comment by deviantfero** [comment]
Hi Dylan, everything seems clear enough, great job, I'll begin to migrate as soon as possible, still I have one suggestion on the individual export functions, wouldn't it be easier to have export types as
`css`, `xresources`, `scss`, etc?

the call to the function would then be: `wal.export(colors, "css", full_path_to_file)` giving a lot more flexibility, if it's to much trouble that's ok, I can rename the files in wpgtk with ease, no big deal, just my two cents.

**Comment by dylanaraps** [comment]
I've implemented what you've suggested @deviantfero.

I've also made some other changes to the api as well as exposed more functions to make it more flexible. Have a look at the wiki page and examples for more info. Again, let me know if there are anymore changes that need to be made. :)

Example:

```py
pywal.export.color(colors, "css", "/home/dylan/colors.css")
pywal.export.color(colors, "sh", "/etc/foo.sh")
```

https://github.com/dylanaraps/pywal/wiki/%5BVery-WIP%5D-How-to-use-the-API#pywalexportcolorcolors-export_type-output_file

**Comment by deviantfero** [comment]
I think it's perfect for now, I think I might come up with a new feature along the way of integrating it to wpgtk, but I'll let you know or maybe do a PR so you can take a look at, final request though, could you detail somewhere in the wiki the format or an example of the `color` dict that is generated and required by all `export` module functions?

**Comment by dylanaraps** [comment]
Awesome, I'll add the `dict` format to the wiki and merge this.

**Comment by dylanaraps** [comment]
I've exposed an additional function to the api which allows you to import colorschemes from `json` files. Python has a `json` module in the standard library which makes it easy to use.

I've also added info about the `dict` format.

- [`pywal.colors.file()`](https://github.com/dylanaraps/pywal/wiki/Using-`pywal`-as-a-module)
- [`dict` format](https://github.com/dylanaraps/pywal/wiki/Using-%60pywal%60-as-a-module#color-dict-format)
- [`json` import file format](https://github.com/dylanaraps/pywal/wiki/Customization#scripting)

Finally a script example using the new function:

- [colors from `json` example](https://github.com/dylanaraps/pywal/wiki/Using-%60pywal%60-as-a-module#example-showing-colors-read-from-json-file)

**Pull request merged**
