### PR TITLE
wallpaper: Add support for macOS

### PR DESCRIPTION
**Pull request by dylanaraps**
This PR aims to add wallpaper setting support to macOS.

@aeikenberry can you test this and let me know if the wallpaper is set correctly?

### CODE REVIEW

**Comment by aeikenberry** [comment]
It sets the colors correctly still, no change on the wallpaper.

**Comment by aeikenberry** [comment]
```
image: Using image /Users/aaron/Dropbox/Wallpapers/gH9EMNA.jpg
wal: Generating a colorscheme...
wal: Generation complete.
7colors: Set terminal colors
osascript: tell: No such file or directory
wallpaper: Set the new wallpaper
export: Exported all files.
reload: Reloaded environment.
```

**Comment by dylanaraps** [comment]
Do these commands work?:

```sh
# Replace "/path/to/img.jpg" with a valid image location.
sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '/path/to/img.jpg'" && killall Dock;

# Replace "/path/to/img.jpg" with a valid image location.
osascript -e 'tell application "System Events" to set picture of every desktop to ("/path/to/img.jpg" as POSIX file as alias)'  
```

**Comment by aeikenberry** [comment]
```
pywal on  macos3 [!] » sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '~/Dropbox/Wallpapers/gH9EMNA.jpg'" && killall Dock;
pywal on  macos3 [!] » osascript -e 'tell application "System Events" to set picture of every desktop to ("~/Dropbox/Wallpapers/gH9EMNA.jpg" as POSIX file as alias)'
2017-07-31 00:45:21.979 osascript[66191:16763821] CFURLGetFSRef was passed an URL which has no scheme (the URL will not work with other CFURL routines)
121:126: execution error: Can’t make file ":~:Dropbox:Wallpapers:gH9EMNA.jpg" into type alias. (-1700)
```
The first one did work, yep.

**Comment by dylanaraps** [comment]
Test out the latest version and let me know if it works.

**Comment by aeikenberry** [comment]
```
pywal on  macos3 [!] » python3 -m pywal -i ~/Dropbox/Wallpapers/gH9EMNA.jpg
image: Using image /Users/aaron/Dropbox/Wallpapers/gH9EMNA.jpg
colors: Found cached colorscheme.
7colors: Set terminal colors
Error: near "/": syntax error
wallpaper: Set the new wallpaper
export: Exported all files.
reload: Reloaded environment.
```
If i change the call to check_output:
```
Error: near "/": syntax error
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaron/code/pywal/pywal/__main__.py", line 130, in <module>
    main()
  File "/Users/aaron/code/pywal/pywal/__main__.py", line 126, in main
    process_args(args)
  File "/Users/aaron/code/pywal/pywal/__main__.py", line 114, in process_args
    wallpaper.change(colors_plain["wallpaper"])
  File "/Users/aaron/code/pywal/pywal/wallpaper.py", line 102, in change
    set_mac_wallpaper(img)
  File "/Users/aaron/code/pywal/pywal/wallpaper.py", line 88, in set_mac_wallpaper
    subprocess.check_output(["sqlite3", db_file, f"update data set value = {img}"])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sqlite3', PosixPath('/Users/aaron/Library/Application Support/Dock/desktoppicture.db'), 'update data set value = /Users/aaron/Dropbox/Wallpapers/gH9EMNA.jpg']' returned non-zero exit status 1.
```

**Comment by aeikenberry** [comment]
if i try to escape the space in Application Support:
```
Error: unable to open database "/Users/aaron/Library/Application\ Support/Dock/desktoppicture.db": unable to open database file
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaron/code/pywal/pywal/__main__.py", line 130, in <module>
    main()
  File "/Users/aaron/code/pywal/pywal/__main__.py", line 126, in main
    process_args(args)
  File "/Users/aaron/code/pywal/pywal/__main__.py", line 114, in process_args
    wallpaper.change(colors_plain["wallpaper"])
  File "/Users/aaron/code/pywal/pywal/wallpaper.py", line 102, in change
    set_mac_wallpaper(img)
  File "/Users/aaron/code/pywal/pywal/wallpaper.py", line 88, in set_mac_wallpaper
    subprocess.check_output(["sqlite3", db_file, f"update data set value = {img}"])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sqlite3', PosixPath('/Users/aaron/Library/Application\\ Support/Dock/desktoppicture.db'), 'update data set value = /Users/aaron/Dropbox/Wallpapers/gH9EMNA.jpg']' returned non-zero exit status 1.
```

**Comment by dylanaraps** [comment]
Thanks, we've just got to get the quoting right with this. I'm trying to avoid using `shell=True` at all costs.

**Comment by dylanaraps** [comment]
Try out this latest commit.

**Comment by aeikenberry** [comment]
This works for me:
`subprocess.call(["sqlite3", db_file, f"update data set value = '{img}'"])`

But i'm not able to commit to this branch.

**Comment by dylanaraps** [comment]
Thanks!

I've pushed a commit with your fix. :)

**Comment by dylanaraps** [comment]
I've pushed a new version to `pypi`, you can `pip3 install` it now. 

Thanks so much for the help. :)

**Pull request merged**
