### PR TITLE
Added iterm2 dynamic profile.

### PR DESCRIPTION
**Pull request by dylanaraps**
TODO:

- [ ] Testing (help!)

How to use:

- Run `wal` on an image.
- Symlink the profile.
    - `ln -s ~/.cache/wal/colors-wal-iterm.plist ~/Library/Application Support/iTerm2/DynamicProfiles/`
- ???

### CODE REVIEW

**Comment by anuragroy11** [comment]
[Screenshot](https://imgur.com/a/pu27s)

**Comment by Towerism** [comment]
I would really like this feature.

**Comment by dylanaraps** [comment]
If possible it'd help if you could test this. I don't have a macOS machine.

**Comment by eramdam** [comment]
@dylanaraps I dont know if you still plan to implement this at some point, but as far as I can tell. This branch works perfectly! 
Screen Shot 2020-05-15 at 10 46 34 PM

**Comment by kdb424** [comment]
Also am running this and can confirm that after a simple rebase on master branch, it's still working.

**Pull request closed without merging**
