### PR TITLE
Add support for #270:  Recursive -i argument

### PR DESCRIPTION
**Pull request by LoLei**
Fix https://github.com/dylanaraps/pywal/issues/270

* Add a new optional command line argument: `--recursive`, to use with `-i`
* Uses all images from subdirectories
* Works with random and iterative method

I tested it with this structure:
```
test-dir
├── dir1
│   ├── dir11
│   │   └── img_dir11.jpg
│   └── img_dir1.jpg
├── dir2
│   ├── img_dir21.JPG
│   └── img_dir2.jpg
├── dir3
│   ├── img_dir3.jpg
│   └── wrong_file_type.sh
├── img_root1.jpg
└── img_root2.jpg
```

Let me know what you think!
<sup>Feel free to sqash the commits btw, I fought with Travis over the indentation of a single line.</sup>

### CODE REVIEW

**Comment by LoLei** [comment]
Hey is anyone gonna look at this? Seems like newer MRs have been merged... @dylanaraps ?

**Comment by dylanaraps** [comment]
LGTM :+1:

I apologize, my backlog across my projects was over 200 different issues and pull requests. I've most likely forgotten some (including this one).

**Comment by LoLei** [comment]
Thanks, and no worries 😎

**Comment by CocolinoFan** [comment]
Great stuff, I can't believe this wasn't a thing already. So what happen to this? 

- `-i` does not look in subdirectories in 2024:  `[E] image: No images found in directory.`

- there is no `--recursive` option: `wal: error: unrecognized arguments: --recursive`

**Comment by LoLei** [comment]
Well it still exists, not sure what's going wrong:

https://github.com/dylanaraps/pywal/blob/master/pywal/__main__.py#L56

**Comment by robwaz** [comment]
I would suggest pulling the project down from GitHub and installing it with `pip -e`.  The version uploaded to pypy has not been updated in a long time. :)

**Comment by CocolinoFan** [comment]
Yep, you are absolutely right, manually cloning the project and then `pip install` that, did the job. Now I can use the `--recursive` argument. 
Maybe we should make it more clear in the install instructions that the pypy version is out of date and that the [manual installation](https://github.com/dylanaraps/pywal/wiki/Installation#manualgit-install) is the remanded method? 
I mean, the `--recursive` is a _really_ basic function. I can imagine quite a lot of people getting frustrated and uninstalling pywal thinking that you can't have it search for images recursively.

**Comment by robwaz** [comment]
I agree, however this project repo has not been updated in 3 years.  So this is simply not possible at the moment unless there is an authoritative fork someone is maintaining.

**Pull request merged**
