### PR TITLE
Added base16 colorschemes

### PR DESCRIPTION
**Pull request by metalelf0**
I added all the available base16 colorschemes (currently 113). I fetched all the listed colorscheme sources from the main base16 site, built a template for the pywal json format, and wrote a little script to build them all. :)

### CODE REVIEW

**Comment by dylanaraps** [comment]
Holy shit! 

Can you post the script? These colorschemes will work with `pywal` though they'll have some minor display issues. What we need to do is map colors `1-6` to match `9-14`. The base16 colors `9-14` are either whites or blacks/greys and they conflict with the way pywal applies colors (vim theme etc).

In the meantime I'll mess around with sed and see if I can do it in a few commands.

**Comment by dylanaraps** [comment]
I'll fix the minor issues post merge.

Thanks for this!

**Comment by dylanaraps** [comment]
Here's the script I used to fix the values if you're interested.

```sh
#!/usr/bin/env bash
mkdir ~/col.out

for file in *.json; do
    jq ".colors.color9  = .colors.color1 |\
        .colors.color10 = .colors.color2 |\
        .colors.color11 = .colors.color3 |\
        .colors.color12 = .colors.color4 |\
        .colors.color13 = .colors.color5 |\
        .colors.color14 = .colors.color6" "$file" > ~/col.out/"${file##*/}"
done
```

**Comment by metalelf0** [comment]
Hey, glad you liked it :) So, right now to build them all I downloaded the [ruby builder](https://github.com/obahareth/base16-builder-ruby), manually added the template to the templates folder and built them. Once the pywal template I made will be added to the list of official templates (I submitted [this PR](https://github.com/chriskempson/base16-templates-source/pull/43)), building the `pywal` colorschemes will be as simple as:

```
git clone https://github.com/obahareth/base16-builder-ruby
cd base16-builder-ruby
bundle
bundle exec ruby builder
```

And you'll have all the schemes in the `out/wal` dir. I also fixed the template to match your latest changes, so all the themes will come out exactly as `pywal` needs them :)

**Comment by dylanaraps** [comment]
I just pushed a new release that contains the base16 themes.

**Pull request merged**
