### PR TITLE
Add zathura template

### PR DESCRIPTION
**Pull request by vxid**
I added a basic template for the zathura document viewer.

Even though it is not documented, it is possible to include files in the default configuration file using:

```
include "~/.cache/wal/colors-zathura"
```

I did not see any way of reloading zathura on the fly though.

### CODE REVIEW

**Comment by vxid** [comment]
Pylint checks are failing for other reasons:

```
************* Module pywal.theme
pywal/theme.py:103:7: R1714: Consider merging these comparisons with "in" to "input_file in ('random', 'random_dark')" (consider-using-in)
pywal/theme.py:116:4: R1705: Unnecessary "else" after "return" (no-else-return)
************* Module pywal.__main__
pywal/__main__.py:109:7: C0113: Consider changing "not len(sys.argv) > 1" to "len(sys.argv) <= 1" (unneeded-not)
************* Module pywal.backends.wal
pywal/backends/wal.py:24:4: R1705: Unnecessary "else" after "return" (no-else-return)

------------------------------------------------------------------
Your code has been rated at 9.96/10 (previous run: 9.96/10, +0.00)
```

**Comment by thy6** [comment]
I use the following template, mostly lifted from the base16 template, it works quite well.

    set default-bg                  "{color0}"
    set default-fg                  "{color10}"
    
    set statusbar-fg                "{color10}"
    set statusbar-bg                "{color0}"
    
    set inputbar-bg                 "{color0}"
    set inputbar-fg                 "{color15}"
    
    set notification-bg             "{color0}"
    set notification-fg             "{color15}"
    
    set notification-error-bg       "{color0}"
    set notification-error-fg       "{color1}"
    
    set notification-warning-bg     "{color0}"
    set notification-warning-fg     "{color1}"
    
    set highlight-color             "{color3}"
    set highlight-active-color      "{color4}"
    
    set completion-bg               "{color10}"
    set completion-fg               "{color4}"
    
    set completion-highlight-fg     "{color15}"
    set completion-highlight-bg     "{color4}"
    
    set recolor-lightcolor          "{color0}"
    set recolor-darkcolor           "{color15}"
    
    set recolor                     "false"
    set recolor-keephue             "false"

**Comment by aleprovencio** [comment]
here's mine:

```
set completion-bg "{color0}"
set completion-fg "{color7}"
set completion-group-bg "{color6}"
set completion-group-fg "{color0}"
set completion-highlight-bg "{color4}"
set completion-highlight-fg "{color7}"
set default-bg "{color0}"
set default-fg "{color7}"
set inputbar-bg "{color6}"
set inputbar-fg "{color0}"
set recolor-lightcolor "{color0}"
set recolor-darkcolor "{color7}"
set statusbar-fg "{foreground}"
set statusbar-bg "{background}"
```

**Comment by dylanaraps** [comment]
The fact that there's 3 different configs tells me this should be handled in user templates instead of being included in pywal.

**Comment by aleprovencio** [comment]
This seems just a matter of taste, can't we get into an agreement to set the best defaults for an official template?

**Comment by deviantfero** [comment]
why not use user templates?

**Comment by aleprovencio** [comment]
I'd would always prefer better defaults than customize.

But if you say pywal's decision on zathura's template is a guideline like, "pywal only ships builtin templates for WMs, Taskbars, and other environment applications; other types of applications are excluded and should be treated as user customization". This makes sense to me.

Anyways, this is just me, I'm sure you guys will come up with a sane decision.

**Comment by vxid** [comment]
I have no preference since I stopped using pywal, but good defaults would be the way to go.

Changing the template posted by @aleprovencio by replacing `color0` and `color7` by `backgrouund` and `foreground` would give defaults everyone can agree on imo.

**Comment by vxid** [comment]
I have no preference since I stopped using pywal, but good defaults would be the way to go.

Changing the template posted by @aleprovencio by replacing `color0` and `color7` by `backgrouund` and `foreground` would give defaults everyone can agree on imo.

**Pull request closed without merging**
