### PR TITLE
Hash file for cache filename

### PR DESCRIPTION
**Pull request by dgrisham**
Addresses https://github.com/dylanaraps/pywal/issues/307. As mentioned there, there are two open questions here:

1. Whether `md5` is appropriate for this application (over, say, `sha256`).
2. Whether this should be an optional feature or the default.

### CODE REVIEW

**Comment by deviantfero** [comment]
I like this addition a lot, but I'm guessing `colors.py` is not the right place for the `hashf` function, consider moving it to the `util.py` module, maybe that's a more appropiate place for that functionality?

you would then call `util.hashf` in `colors.py`

**Comment by dgrisham** [comment]
@deviantfero Good call :+1: I didn't pay enough attention to the existing setup while adding this.

**Comment by dgrisham** [comment]
In the example I gave in https://github.com/dylanaraps/pywal/issues/307, the filename looked like:

`e57c9a6627a5c51244b65e88e50539ab_dark_wal__1.1.0.json`

it might be worth hashing all of the info together (so, add in the `dark`, `wal`, and version number), rather than have a partially (but not completely) human readable filename.

Thoughts?

**Comment by deviantfero** [comment]
I think it's better to keep the other information readable.

**Comment by dgrisham** [comment]
Cool, I'm on board with that.

Is there anyone who can merge this aside from @dylanaraps? Looks like he hasn't been active on github for a few months.

**Comment by deviantfero** [comment]
I don't think there is, anyway you should try to fix those Travis CI errors

**Comment by dylanaraps** [comment]
Fix the lint errors and I'll merge this :+1:

**Comment by dgrisham** [comment]
:+1: @dylanaraps fixed the ones that I introduced -- there were a couple of other small ones that I left because they were already there and not particularly bad, but I can get rid of those too if you'd prefer.

**Comment by dylanaraps** [comment]
Cheers :+1:

**Comment by dylanaraps** [comment]
Reverting this till I can test the performance impact.

**Pull request merged**
