### PR TITLE
Added random function

### PR DESCRIPTION
**Pull request by chrissparksnj**
The` --random `argument uses the [source.unsplash.com](https://source.unsplash.com/) random feature to search for user provided input and set colors based on a random photo relevant to search term.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks for the PR.

I'm really against adding network functionality to `pywal`. This can very easily be done with a simple shell-script and `curl`/`wget`. I don't think this feature belongs at all.

**Comment by chrissparksnj** [comment]
> Thanks for the PR.
> 
> I'm really against adding network functionality to `pywal`. This can very easily be done with a simple shell-script and `curl`/`wget`. I don't think this feature belongs at all.

i kind of figured you didn't like network functionality so that's why I used urllib instead of requests.

but when a user is in a cloud environment and a shell is all they have access to. 

- looking up the photo through your browser
- using wget to download the url
- and then running pywal to make a color scheme.

This forces me to leave the shell.

With this function, you can just run the option with a search term and not have to ever leave the shell.

**Comment by dylanaraps** [comment]
See:

> This can very easily be done with a simple shell-script and `curl`/`wget`.

Nothing stops this from being automated in a shell-script.

**Comment by chrissparksnj** [comment]
very true. 

you can close it then, and i will keep it stored locally and put
`wal --random happy` in my  `.bashrc` file.

**Pull request closed without merging**
