### PR TITLE
Add fish completions

### PR DESCRIPTION
**Pull request by GloverDonovan**
Hello,

Thank you for making pywal. Since I enjoy using pywal, I made fish completions for it. This is how it looks:

Screenshot 1

Screenshot 2

Let me know what you think.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Can we remove the hard coded theme, backend etc references? You can parse —backend and —theme to get a list (or you can get the file from their directories directly).

**Comment by dylanaraps** [comment]
I can add some hidden flags to pywal to print the information in a way that can be used with completions.

**Comment by GloverDonovan** [comment]
That would be great. If possible, I think pywal should return the themes and descriptions in one go for shell completions. Then it would be up to each individual shell to parse the results since each one has a different completion syntax.

**Comment by dylanaraps** [comment]
I don't think I want to add completions.

**Pull request closed without merging**
