### PR TITLE
fix 495

### PR DESCRIPTION
**Pull request by patzm**

### CODE REVIEW

**Comment by patzm** [comment]
Damn, didn't see that this is a duplicate of #485.

**Comment by SrKomodo** [comment]
Just as #485, the CI tests fail due to there being too many local variables. They can either be reduced to a maximum of 15, or you can disable the lint by adding `# pylint: disable-msg=too-many-locals` at the beginning of the function.

**Comment by patzm** [comment]
Thx @SrKomodo, I opted for ignoring this rule in 0d664396205c3bbd56924de611b1921cf641e48e. I currently don't have the time to do refactoring. After all, this code is a bit convoluted anyways. Hence, spending time on refactoring should also produce a clearer and more pythonic implementation.

PS: I hope this doesn't offend anyone here :wink: This code get's the job done.

**Comment by patzm** [comment]
Now obsolete after #485 got merged.

**Pull request closed without merging**
