### PR TITLE
[Enhancement] #305: Add indication next to previous theme when running wal --theme

### LINKED ISSUE #305: Add symbol next to active theme when running wal --theme
It would be nice to differentiate the active theme from the others by having a symbol next to it.

### PR DESCRIPTION
**Pull request by LoLei**
### Regarding #305:
* Prints `(last used`) next to last used theme when listing themes with `--theme`.

I couldn't decide on a symbol to use, so I just used text. If @ghost or someone else has a suggestion, feel free to let me know.

-- 
Closes #305

### CODE REVIEW

**Comment by dylanaraps** [comment]
Can I see a screenshot of what this looks like? I like the idea. :+1:

**Comment by LoLei** [comment]
Sure, e.g.:  
...  

...  

Credit for the idea goes to @ghost

**Comment by dylanaraps** [comment]
@ghost is a "dummy account" which acts as "blank information" after a user deletes their GitHub account.

**Comment by LoLei** [comment]
Huh I never knew that. Thanks for the merge!

**Pull request merged**
