### PR TITLE
themes: Initial theme support

### PR DESCRIPTION
**Pull request by dylanaraps**
- `wal -f` lists all available built-in themes.
- `wal -f theme-name` applies a theme.
- `wal -f random` applies a theme at random.
- Themes can be added locally at `~/.config/wal/colorschemes`.
- `wal -f` can be used with colorschemes exported in json format from https://terminal.sexy/.

### CODE REVIEW

**Comment by deviantfero** [comment]
in what format will pywal accept colorschemes? I've been thinking of implementing this feature on `wpgtk` but if it's implemented on pywal it would be really cool, too.

I had in mind being able to pull a colorscheme from a site like https://terminal.sexy in some format that they offer and parse the colors from a textfile generated there, they have lots of popular themes.

**Comment by dylanaraps** [comment]
Have a look at the json files in this PR.

We could support terminal.sexy json scheme output but we'd need to change our format to match it. The only difference is how the numbered colors are stored. terminal.sexy uses a list while pywal uses dicts.

```json
{
  "name": "",
  "author": "",
  "color": [
    "#282a2e",
    "#a54242",
    "#8c9440",
    "#de935f",
    "#5f819d",
    "#85678f",
    "#5e8d87",
    "#707880",
    "#373b41",
    "#cc6666",
    "#b5bd68",
    "#f0c674",
    "#81a2be",
    "#b294bb",
    "#8abeb7",
    "#c5c8c6"
  ],
  "foreground": "#c5c8c6",
  "background": "#1d1f21"
}
```

**Comment by deviantfero** [comment]
how about iterating the color list that `terminal.sexy` provides to acommodate it to a normal `pywal` format, something like...

```
tsexy  = json.parse(file) # w/e you get the idea
tsexy['colors'] = {}
for each n, c in ennumerate(tsexy.color):
   tsexy.colors['color%d' % n] = c
# delete tsexy.color since it's no longer needed
```

just a rough idea, don't take to seriously, anyway I would like to implement it to `wpgtk` if this is too out of scope for pywal.

**Comment by dylanaraps** [comment]
I've added support for terminal.sexy json exports.

**Comment by deviantfero** [comment]
I'll wait for the official release before I add support to `wpgtk`, this is great :ok_hand:

**Pull request merged**
